FROM ubuntu:22.04

# Make use of bash, not the system shell
RUN mv /bin/sh /bin/sh.bak && ln -s /bin/bash /bin/sh

######################
# WORK FILES
######################

WORKDIR ./server/
COPY ./package*.json ./

######################
# ROS2 Humble Install
######################

# Check language locale
RUN lang_locale=$(locale | grep "LANG=")
RUN anticipated_locale="LANG=en_US.UTF-8"

# Assign and install locale if there is an issue
# LONG IF STATEMENT
RUN  if [ $lang_locale != $anticipated_locale ]; then apt update; apt install locales; locale-gen en_US en_US.UTF-8; update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8; export LANG=en_US.UTF-8; echo "----------------------"; echo "Locale has been updated"; fi

# Add sources
RUN apt install software-properties-common -y
RUN add-apt-repository universe
# Update the repositories again
# Install curl, quiet automatic yes
RUN apt update && apt install curl -y
# ROS 2 specific, GPG key for the repository
RUN curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
# Add the ROS 2 repository
RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | tee /etc/apt/sources.list.d/ros2.list > /dev/null

# Update package repository data and upgrade packages
RUN apt update && apt upgrade -y

# Prevent interactive requests from tzdata
# Install ROS2 humble from official repo
RUN export DEBIAN_FRONTEND="noninteractive"; apt install ros-humble-ros-base ros-dev-tools -y

# ROS2 has installed, yay
RUN echo "ROS2 installed!"
######################

ADD ./* .

# Install NVM
# RUN curl https://raw.githubusercontent.com/creationix/nvm/v0.20.0/install.sh | bash \
#     && . /root/.nvm/nvm.sh \
#     # NVM is not creating a versions directory
#     && mkdir /root/.nvm/versions \
#     && nvm install 20.9.0 \
#     # Install node packages
#     && source /opt/ros/humble/setup.bash \
#     && npm install

# Add repo key
RUN apt update
RUN apt install -y ca-certificates curl gnupg
RUN mkdir -p /etc/apt/keyrings
RUN curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
# Add repository
RUN echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list
RUN apt update
# Install node version
RUN apt install nodejs -y
# Source ROS, install node packages
RUN source /opt/ros/humble/setup.bash && npm install
# Build the Typescript
RUN source /opt/ros/humble/setup.bash && npm run build 

CMD ["/bin/bash", "-c", "source /opt/ros/humble/setup.bash && npm start"]
